version: '3'

services:

  db:
    image: zmbrahian/timeoff-db:1.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: ./
      dockerfile: ./docker-compose/mysql.Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "rut4lt3rn4"
      MYSQL_USER: "userdba"
      MYSQL_PASSWORD: "rut4lt3rn4"

  app:
    image: zmbrahian/timeoff-webapp:1.0
    restart: always
    build:
      context: ./
      dockerfile: ./docker-compose/app.Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - "db"