name: build_test_and_deploy_app.yml
run-name: Execution triggered by ${{ github.actor }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 13.x, 14.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies    
        run: npm install
      - name: Installing chromedriver
        run: mkdir -p /tmp/bin && curl -o /tmp/bin/chromedriver https://chromedriver.storage.googleapis.com/108.0.5359.71/chromedriver_linux64.zip && chmod u+x /tmp/bin/chromedriver && export PATH="$PATH:/tmp/bin/"
      - name: Run Unit tests
        run: npm test
